# Generated by Django 4.1.6 on 2023-07-18 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonDRF', '0002_rating_remove_menuitem_category_delete_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='category',
            new_name='user',
        ),
    ]
